"$schema" = "https://starship.rs/config-schema.json"

format = """
[](#facc15)\
$os\
$username\
[](bg:#fb923c fg:#facc15)\
$directory\
[](fg:#fb923c bg:#22c55e)\
$git_branch\
$git_status\
[](fg:#22c55e bg:#facc15)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$lua\
[](fg:#facc15 bg:#2dd4bf)\
$docker_context\
[ ](fg:#2dd4bf)\
\n$character
"""

add_newline = true

[username]
show_always = true
style_user = "bg:#facc15 fg:#020617"
style_root = "bg:#facc15 fg:#020617"
format = "[$user ]($style)"

[directory]
style = "bg:#fb923c fg:#020617"
format = "[ $path ]($style)"
truncate_to_repo = false
truncation_length = 1000
home_symbol = "~"

[git_branch]
symbol = ""
style = "bg:#22c55e fg:#020617"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#22c55e fg:#020617"
format = "[$all_status$ahead_behind ]($style)"

[c]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[cpp]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[elixir]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[elm]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[golang]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[gradle]
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[haskell]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[java]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[julia]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[nodejs]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[nim]
symbol = "󰆥 "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[rust]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[scala]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[lua]
symbol = " "
style = "bg:#facc15 fg:#020617"
format = "[ $symbol ($version) ]($style)"

[docker_context]
symbol = " "
style = "bg:#2dd4bf fg:#020617"
format = "[ $symbol $context ]($style)"

[character]
success_symbol = "[](bold fg:#22c55e)"
error_symbol = "[](bold fg:#ef4444)"
vicmd_symbol = "[](bold fg:#facc15)"

